
export const action ={
    LOGIN_REQUEST : 'LOGIN_REQUEST',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    MODAL_SESSION:"MODAL_SESSION",
    GALLERY_REQUEST:"GALLERY_REQUEST",
    SHOW_ALBUM: "SHOW_ALBUM",
    ADD_IMAGE: "ADD_IMAGE",
    INSERT_IMAGE: "INSERT_IMAGE"
}